spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roleplaying?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: lunan998998
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # ???????????????

ai:
  asr:
    endpoint: https://asr.aliyun.com/api  # ????????
    key: your_asr_key
  tts:
    endpoint: https://tts.aliyun.com/api
    key: your_tts_key
  llm:
    endpoint: https://dashscope.aliyuncs.com/api/v1/services/inference
    key: your_qwen_key